### ISSUE TITLE
adding a static site generator to reuse header and footer

### ISSUE THREAD

**Issue by dhmlau** [strongloop/v4.loopback.io#14]
From @virkt25 
> We should look into adding a static site generator so we can separate the site header / footer for reuse -- I'm thinking a Node based one (VuePress looks promising)

## Acceptance Criteria
- [ ] Pick a static site generator 
   - @virkt25 suggested [VuePress](https://vuepress.vuejs.org/) or [Hexo](https://hexo.io/)
- [ ] create the site header and footer as template using the static site generator

**Comment by dhmlau** [comment]
@virkt25 , you have more details on it.  could you please see if the acceptance criteria make sense, otherwise edit accordingly?  thanks.

**Comment by virkt25** [comment]
That looks good to me, I personally think we should try `VuePress` out of the two choices. As a follow up task to this, once we have the `docs` page implemented -- we should update the doc markdown files to the appropriate front-matter + change code highlighting (if needed) to make use of features such as line highlighting, etc.

**Comment by ui-guys** [comment]
Is this open to suggestions? If yes, why not look at Gatsby

**Comment by virkt25** [comment]
@ui-guys Since the task hasn't been started, it's most certainly open to suggestion. My preference for VuePress is mostly because it's designed for technical documentation whereas Gatsby looks like a jack of all trades. 

Can you share some benefits of Gatsby / share a repo where it's used for technical documentation so I can see how it's done / how easy / complicated it is.

Also, would you be interested in contributing?

**Comment by dhmlau** [comment]
See PR https://github.com/strongloop/v4.loopback.io/pull/45

**Comment by dhmlau** [comment]
Closing it as irrelevant. We have moved the v4.loopback.io pages to loopback.io, and reusing the loopback.io docs infrastructure.
